@startuml

interface ReprodutorMusical {
    + tocar()
    + pausar()
    + selecionarMusica()
}

interface AparelhoTelefonico {
    + ligar()
    + atender()
    + iniciarCorreioVoz()
}

interface NavegadorInternet {
    + exibirPagina()
    + adicionarNovaAba()
    + atualizarPagina()
}

class IPhone implements ReprodutorMusical, AparelhoTelefonico, NavegadorInternet {
    + tocar()
    + pausar()
    + selecionarMusica()
    + ligar()
    + atender()
    + iniciarCorreioVoz()
    + exibirPagina()
    + adicionarNovaAba()
    + atualizarPagina()
}

@enduml